/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Controller.movieController;
import Dao.loginpagedao;
import Model.Movie_add;

import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import java.awt.Image; // Make sure this is imported at the top
import java.text.SimpleDateFormat;
import java.util.List;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import java.awt.Component;


/**
 *
 * @author Kohinoor
 */
public class Admin_1 extends javax.swing.JFrame {

    private movieController movieController = new movieController();
     private File selectedImageFile; 
    /**
     * Creates new form Admin_1
     */
    public Admin_1() {
         initComponents();
SpinnerDateModel dateModel = new SpinnerDateModel();
        DateSpinner.setModel(dateModel);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(DateSpinner, "MMM dd, yyyy");
        DateSpinner.setEditor(editor);
        DateSpinner.setValue(new java.util.Date());
        // Populate the table with movies
        populateTable(); // Call to populate the table with movie data
        // Set the custom renderer for the image column (assuming it's the 6th column)
        Movie_Table.getColumnModel().getColumn(5).setCellRenderer(new ImageRenderer());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Movie_Table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Movie_Title = new javax.swing.JTextField();
        Genre_ComboBox = new javax.swing.JComboBox<>();
        btnImport = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        DateSpinner = new javax.swing.JSpinner();
        Duration = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SynopisScroll = new javax.swing.JScrollPane();
        Synopsis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(122, 106, 106));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/admin.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add  movies");

        LogutBtn.setBackground(new java.awt.Color(122, 106, 106));
        LogutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogutBtn.setText("LOG OUT");
        LogutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogutBtn)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(LogutBtn)
                .addGap(62, 62, 62))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        Movie_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Movie ID ", "Movie Title", "Gerne", "Duration", "Show Date", "Images", "Price"
            }
        ));
        Movie_Table.setRowHeight(75);
        Movie_Table.setShowGrid(true);
        jScrollPane2.setViewportView(Movie_Table);

        jLabel6.setText("Movie ID");

        jLabel7.setText("Movie Title");

        jLabel8.setText("Gerne");

        jLabel9.setText("Duration");

        jLabel10.setText("Show Date");

        jLabel11.setText("Movie Synopsic");

        Movie_Title.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Movie_TitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Movie_TitleFocusLost(evt);
            }
        });

        Genre_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categories", "Action", "Comedy", "Drama", "Horror", "Fantasy", "Romance", "Thriller", "Sci-Fi", "Animation" }));
        Genre_ComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Genre_ComboBoxFocusGained(evt);
            }
        });
        Genre_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genre_ComboBoxActionPerformed(evt);
            }
        });

        btnImport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnImport.setText("IMPORT");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        Add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        imageLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        imageLabel.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel4.setText("Price");

        Synopsis.setColumns(20);
        Synopsis.setRows(5);
        SynopisScroll.setViewportView(Synopsis);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel10)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Duration)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Movie_Title, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Genre_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 157, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnImport)
                                        .addGap(175, 175, 175))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(Delete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(138, 138, 138))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Price)
                                    .addComponent(DateSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Add))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(SynopisScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Movie_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Genre_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImport))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(88, 88, 88))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(SynopisScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))
                .addComponent(Add)
                .addGap(21, 21, 21))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


private void AddActionPerformed(java.awt.event.ActionEvent evt) {                                                                       
    String input = Duration.getText().trim();
    if (!input.matches("^\\d{1,2}:\\d{2}:\\d{2}$")) {
        JOptionPane.showMessageDialog(this, "Enter duration as HH:mm:ss");
        return;
    }
    
    String[] parts = input.split(":");
    int h = Integer.parseInt(parts[0]);
    int m = Integer.parseInt(parts[1]);
    int s = Integer.parseInt(parts[2]);
    if (h < 0 || h > 23 || m < 0 || m > 59 || s < 0 || s > 59) {
        JOptionPane.showMessageDialog(this, "Invalid duration values");
        return;
    }
    
    java.util.Date selectedDate = (java.util.Date) DateSpinner.getValue(); 
    SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
    String formattedDate = sdf.format(selectedDate);
    
    String title = Movie_Title.getText().trim();
    String genre = Genre_ComboBox.getSelectedItem().toString();
    if (genre.equals("Categories")) {
        JOptionPane.showMessageDialog(this, "Please select a valid genre.");
        return;
    }
    String synopsis = Synopsis.getText().trim();
    String duration = String.format("%02d:%02d:%02d", h, m, s);

    String priceStr = Price.getText().trim();
double price;
try {
    price = Double.parseDouble(priceStr);
    if(price < 0) {
        JOptionPane.showMessageDialog(this, "Price cannot be negative.");
        return;
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Enter a valid price (number).");
    return;
}

    String imagePath = "";
    try {
        if (selectedImageFile != null) {
            File destDir = new File("src/images/");
            if (!destDir.exists()) {
                destDir.mkdirs();
            }
            File destFile = new File(destDir, selectedImageFile.getName());
            java.nio.file.Files.copy(
                selectedImageFile.toPath(),
                destFile.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );
            imagePath = destFile.getName();
        }

        movieController.addMovie(title, genre, synopsis, duration, formattedDate, imagePath, price);
        JOptionPane.showMessageDialog(this, "Movie added successfully!");

        // Show saved image in label
        if (!imagePath.isEmpty()) {
            String fullPath = "src/images/" + imagePath;
            ImageIcon icon = new ImageIcon(fullPath);
            Image img = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        }

        clearFields();
        selectedImageFile = null;
        populateTable();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saving movie or image: " + e.getMessage());
    }

}


    

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select an Image");
    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(
        new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif"));

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File sourceFile = fileChooser.getSelectedFile();
        selectedImageFile = sourceFile; // keep reference to original file

        // Show preview on imageLabel
        ImageIcon icon = new ImageIcon(selectedImageFile.getAbsolutePath());
        Image img = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
    }
    }//GEN-LAST:event_btnImportActionPerformed

    private void Genre_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genre_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Genre_ComboBoxActionPerformed

    private void Movie_TitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Movie_TitleFocusGained
 if (Movie_Title.getText().equals("Title")) {
            Movie_Title.setText(""); 
 }       // TODO add your handling code here:
    }//GEN-LAST:event_Movie_TitleFocusGained

    private void Movie_TitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Movie_TitleFocusLost
if(Movie_Title.getText ().isEmpty()){
            Movie_Title.setText("Title");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Movie_TitleFocusLost

    private void clearFields() {
    // Clear input fields
    ID.setText("");                     // Clear the ID field
    Movie_Title.setText("");            // Clear the Movie Title field
    Duration.setText("");               // Clear the Duration field
    Synopsis.setText("");               // Clear the Synopsis field
    // Reset the Genre ComboBox to the default selection
    Genre_ComboBox.setSelectedIndex(0); // Assuming the first item is a placeholder
    // Clear the image label
    imageLabel.setIcon(null);           // Remove any displayed image
    // Reset the DateSpinner to the current date
    DateSpinner.setValue(new java.util.Date()); // Reset to current date
}

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        String id = ID.getText().trim();
    
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Movie ID to delete.");
        return;
    }
    
    try {
        int movieId = Integer.parseInt(id);
        movieController.deleteMovie(movieId); // Call the delete method
        JOptionPane.showMessageDialog(this, "Movie deleted successfully!");
        clearFields(); // Clear the fields after deletion
        populateTable(); // Refresh the table
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Movie ID. Please enter a valid number.");
    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage()); // Show error message from deleteMovie
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting movie: " + e.getMessage());
    }
}
//GEN-LAST:event_DeleteActionPerformed

    private void Genre_ComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Genre_ComboBoxFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Genre_ComboBoxFocusGained

  private void LogutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogutBtnActionPerformed
    int response = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to log out?",
        "Confirm Logout",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    if (response == javax.swing.JOptionPane.YES_OPTION) {
        System.out.println("Logging out..."); // Debugging line
        // Create a new instance of loginPage2
        loginPage2 loginView = new loginPage2();
        loginpagedao loginDao = new loginpagedao(); // Assuming you have a DAO for login
        Controller.loginpageController loginController = new Controller.loginpageController(loginView, loginDao);
        
        // Open the login page using the controller
        loginController.open();
        // Dispose of the current Admin_1 window
        this.dispose();
    }
}//GEN-LAST:event_LogutBtnActionPerformed


    
    private void populateTable() {
   List<Movie_add> movies = movieController.getAllMovies(); 
    DefaultTableModel model = (DefaultTableModel) Movie_Table.getModel();
    model.setRowCount(0);

    for (Movie_add movie : movies) {
        String imageFilename = movie.getImagePath();
        ImageIcon icon = null;

        if (imageFilename != null && !imageFilename.isEmpty()) {
            String imagePath = "src/images/" + imageFilename;
            File imgFile = new File(imagePath);
            System.out.println("Checking image file: " + imgFile.getAbsolutePath());
            if (imgFile.exists()) {
                try {
                    ImageIcon originalIcon = new ImageIcon(imagePath);
                    Image img = originalIcon.getImage().getScaledInstance(50, 75, Image.SCALE_SMOOTH);
                    icon = new ImageIcon(img);
                    System.out.println("Image loaded successfully for movie: " + movie.getTitle());
                } catch (Exception e) {
                    System.err.println("Error loading image for " + movie.getTitle() + ": " + e.getMessage());
                }
            } else {
                System.out.println("Image file NOT found: " + imgFile.getAbsolutePath());
            }
        } else {
            System.out.println("No image path for movie: " + movie.getTitle());
        }

        model.addRow(new Object[]{
            movie.getId(),
    movie.getTitle(),
    movie.getGenre(),
    movie.getDuration(),
    movie.getShowDate(),
    icon,
    movie.getPrice()
        });
    }
}

    

public class ImageRenderer extends DefaultTableCellRenderer {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, 
        boolean isSelected, boolean hasFocus, int row, int column) {

        if (value instanceof ImageIcon) {
            JLabel label = new JLabel();
            label.setIcon((ImageIcon) value);
            label.setHorizontalAlignment(JLabel.CENTER);
            if (isSelected) {
                label.setBackground(table.getSelectionBackground());
                label.setOpaque(true);
            } else {
                label.setOpaque(false);
            }
            return label;
        }
        return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
    }
}





    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JSpinner DateSpinner;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Duration;
    private javax.swing.JComboBox<String> Genre_ComboBox;
    private javax.swing.JTextField ID;
    private javax.swing.JButton LogutBtn;
    private javax.swing.JTable Movie_Table;
    private javax.swing.JTextField Movie_Title;
    private javax.swing.JTextField Price;
    private javax.swing.JScrollPane SynopisScroll;
    private javax.swing.JTextArea Synopsis;
    private javax.swing.JButton btnImport;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
