/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Dao.MovieDAO;
import Dao.PaymentDAO;
import Model.Movie_add;
import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import view.Cancel_Booking;


/**
 *
 * @author Kohinoor
 */
public class Movie_Detail1 extends javax.swing.JFrame {
    private Movie_add currentMovie;
    private MovieDAO movieDAO = new MovieDAO();
    private int currentUserId;
    private String bookedSeats = "";
    private double bookingPrice = 0.0;
    /**
     * Creates new form Movie_Detail1
     */
    public Movie_Detail1(Movie_add movie, int userId) {
    initComponents();
    TitleLabel.setText(movie.getTitle());
    GenreLabel.setText(movie.getGenre());
    Duration.setText(movie.getDuration());
    PriceLabel.setText(String.format("Rs. %.2f", movie.getPrice()));
    Show_DateLabel.setText(movie.getShowDate());
    Synposis.setText(movie.getSynopsis());
    Synposis.setEditable(false);

    String imagePath = "src/images/" + movie.getImagePath();
    File imgFile = new File(imagePath);
    if (imgFile.exists()) {
        ImageIcon icon = new ImageIcon(imagePath);
        java.awt.Image scaledImage = icon.getImage().getScaledInstance(Image.getWidth(), Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
        Image.setIcon(new ImageIcon(scaledImage));
        Image.setText("");
    } else {
        Image.setText("No Image");
        Image.setIcon(null);
    }

    this.currentMovie = movie;
    this.currentUserId = userId;

    MovieDAO movieDAO = new MovieDAO();
    FavButton.setSelected(movieDAO.isFavorite(currentUserId, currentMovie.getId()));
    WatchlistBtn.setSelected(movieDAO.isInWatchlist(currentUserId, currentMovie.getId()));

    PaymentDAO paymentDAO = new PaymentDAO();
    boolean hasBooking = paymentDAO.hasBooking(currentUserId, currentMovie.getTitle());
    boolean canCancel = false;

    if (hasBooking) {
        bookedSeats = paymentDAO.getBookedSeats(currentUserId, currentMovie.getTitle());
        bookingPrice = paymentDAO.getBookingPrice(currentUserId, currentMovie.getTitle());
        String showDateStr = currentMovie.getShowDate();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        try {
            LocalDate showDate = LocalDate.parse(showDateStr, formatter);
            LocalDate today = LocalDate.now();
            long daysBetween = ChronoUnit.DAYS.between(today, showDate);
            canCancel = daysBetween >= 2;
        } catch (Exception e) {
            e.printStackTrace();
            canCancel = false;
        }
    }
    CancelBook.setEnabled(hasBooking && canCancel);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        Booking = new javax.swing.JButton();
        CancelBook = new javax.swing.JButton();
        Image = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Synposis = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Show_DateLabel = new javax.swing.JLabel();
        Review = new javax.swing.JButton();
        FavButton = new javax.swing.JToggleButton();
        WatchlistBtn = new javax.swing.JToggleButton();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(122, 106, 106));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Synopsis");

        Duration.setForeground(new java.awt.Color(255, 255, 255));
        Duration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Booking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Booking.setText("Booking");
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });

        CancelBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CancelBook.setText("Cancel Booking");
        CancelBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookActionPerformed(evt);
            }
        });

        Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        PriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        PriceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Genre");

        GenreLabel.setForeground(new java.awt.Color(255, 255, 255));
        GenreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Duration");

        Synposis.setColumns(20);
        Synposis.setRows(5);
        jScrollPane1.setViewportView(Synposis);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");

        Show_DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        Show_DateLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Review.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Review.setText("Review");
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });

        FavButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart_empty.png"))); // NOI18N
        FavButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FavButton.setFocusPainted(false);
        FavButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart_filled.png"))); // NOI18N
        FavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavButtonActionPerformed(evt);
            }
        });

        WatchlistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        WatchlistBtn.setBorderPainted(false);
        WatchlistBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        WatchlistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatchlistBtnActionPerformed(evt);
            }
        });

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow-50.png"))); // NOI18N
        BackBtn.setFocusPainted(false);
        BackBtn.setFocusable(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Booking)
                                    .addGap(47, 47, 47)
                                    .addComponent(CancelBook))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Review)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(WatchlistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Show_DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WatchlistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Show_DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(GenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(18, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Booking)
                    .addComponent(CancelBook)
                    .addComponent(Review))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {
    int movieId = Integer.parseInt(currentMovie.getId());
    int userId = currentUserId;
    String movieTitle = currentMovie.getTitle();
    int pricePerSeat = (int) currentMovie.getPrice();

    String showDateStr = currentMovie.getShowDate(); // e.g., "2025-06-20"
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    LocalDateTime showtime;
    try {
        LocalDate showDate = LocalDate.parse(showDateStr, formatter);
        LocalDate today = LocalDate.now();

        // ⛔ Prevent booking if the show date is before today
        if (showDate.isBefore(today)) {
            JOptionPane.showMessageDialog(this, "This show's booking date has already passed.");
            return;
        }

        showtime = showDate.atStartOfDay(); // Convert to LocalDateTime if needed
    } catch (DateTimeParseException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Invalid show date format: " + showDateStr);
        return;
    }

    // Proceed with booking
    view.seat_planning_GUI seatGui = new view.seat_planning_GUI(
        movieId, userId, movieTitle, pricePerSeat, showtime
    );
    Dao.seat_dao seatDao = new Dao.seat_dao();
    Controller.seat_controller seatController = new Controller.seat_controller(
        seatGui, seatDao, movieId, userId, showtime
    );

    seatGui.setController(seatController);
    seatGui.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BookingActionPerformed

    private void FavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavButtonActionPerformed
         MovieDAO movieDAO = new MovieDAO(); // create DAO instance
    if (FavButton.isSelected()) {
        movieDAO.addToFavorites(currentUserId, currentMovie.getId()); // Pass userId
    } else {
        movieDAO.removeFromFavorites(currentUserId, currentMovie.getId()); // Pass userId
    }// TODO add your handling code here:
    }//GEN-LAST:event_FavButtonActionPerformed

    private void WatchlistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatchlistBtnActionPerformed
          MovieDAO movieDAO = new MovieDAO(); // create DAO instance
    if (WatchlistBtn.isSelected()) {
        movieDAO.addToWatchlist(currentUserId, currentMovie.getId()); // Pass userId
    } else {
        movieDAO.removeFromWatchlist(currentUserId, currentMovie.getId()); // Pass userId
}// TODO add your handling code here:
    }//GEN-LAST:event_WatchlistBtnActionPerformed

    private void CancelBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookActionPerformed
         if (!CancelBook.isEnabled()) {
        JOptionPane.showMessageDialog(this, "Cancellation is only allowed until 2 days before the showtime.");
        return;
    }
    
    if (bookedSeats.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No booking found to cancel.");
        return;
    }

    Cancel_Booking cancelBookingPage = new Cancel_Booking(currentUserId, currentMovie.getTitle(), bookedSeats, bookingPrice);
    cancelBookingPage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_CancelBookActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
Dashboard dashboard = new Dashboard(currentUserId);
        dashboard.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
         int userId = this.currentUserId;
    int movieId = Integer.parseInt(currentMovie.getId());  // assuming getId() returns String, parse to int
    
    // Assuming your Review JFrame has a constructor that accepts userId and movieId
    Review reviewForm = new Review(userId, movieId);
    reviewForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ReviewActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Movie_Detail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Movie_Detail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Movie_Detail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Movie_Detail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Movie_Detail1().setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Booking;
    private javax.swing.JButton CancelBook;
    private javax.swing.JLabel Duration;
    private javax.swing.JToggleButton FavButton;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JButton Review;
    private javax.swing.JLabel Show_DateLabel;
    private javax.swing.JTextArea Synposis;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JToggleButton WatchlistBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
